### ISSUE TITLE
GridLayout broken

### ISSUE THREAD

**Issue by hfhbd** [hfhbd/bootstrap-compose#112]
Noticed by @gsteckman:
The GridLayout isn't working with the latest version updates. I am getting the runtime error in the javascript console "Uncaught TypeError: elements.iterator_0_k$ is not a function" when going to the Grid Layout view in the showcase. I traced it down to the code in Styling.kt lines 36-38 (if you comment that out, the error stops, but of course then it doesn't apply all the styling). I tried making a small test to reproduce the error and isolate the issue, but have not been able to reproduce it yet. It's probably something with the compose or javascript compilers since the kotlin compiles ok. It looks like the components that use Styling.generate() are broken.

**Comment by hfhbd** [comment]
Thanks for noticing! I don't use GridLayout, so I didn't notice this in my production app...
I have to create tests for every component to automate the current manual test using showcase! But unfortunately I am currently busy too. I will take a short look later this day, but I can't promise anything.

**Comment by gsteckman** [comment]
It appears to be fixed in the latest update: id("org.jetbrains.compose") version "1.0.0-alpha4-build331". Possibly from the commit 49bfb89c117db78552c888d90a6b8461ecd6bd1e.

**Comment by hfhbd** [comment]
Yeah, it looks like it is fixed. Feel free to reopen if not.
