### ISSUE TITLE
Table header z-index setting

### ISSUE THREAD

**Issue by gsteckman** [hfhbd/bootstrap-compose#145]
If fixedHeader != null, the "sticky-top" bootstrap class is applied to the header which sets a z-index value of 1020. However, a style property is applied (Table.kt, line 368) that sets the z-index value to "auto", which overrides the class provided value. This setting was added in pull #75 - but setting to auto does not always provide the desired effect because if a sticky header is used some table content might render above the header.

If the z-index value is not set in the Table function, the user could still override the sticky-top setting of the z-index value by using the attrs value in the Header class. So I propose removing this from the Table function.

**Comment by hfhbd** [comment]
Thanks! I noticed it too, but was unable to find the solution.
