### ISSUE TITLE
NavbarDropDown does not work if a composable with a modal in it is not included in project

### ISSUE THREAD

**Issue by luca992** [hfhbd/bootstrap-compose#185]
So I couldn't get NavbarDropDown items to work (nothing pops up when you click them) in my project.
I managed to create simple example with the showcase project and removing everything that wasn't relevant.

https://github.com/luca992/bootstrap-compose/tree/NavbarDropDownIssue

For some reason, if a composable with a modal in it is not included in the project, the NavbarDropDown will not pop up. I commented out ModalView.kt in the example. If ModalView.kt is uncommented it will work as expected.... and it's not even called. Weird.

**Comment by hfhbd** [comment]
Thanks for the report, but it's not weird :D Webpack optimized your simplified code, which does not uses bootstrap js (model imports it by using the annotation). Many components requires only css.

As a workaround, you could enforce the compiler to import bootstrap itself: 
```kotlin
@JsModule("bootstrap")
@JsNonModule
external val dummy: String
```
and call it:
```kotlin
fun main() {
    dummy
    renderComposable(rootElementId = "root") {
    }
}
```
A better workaround would be fixing the web pack config, but I am not an JS expert, and web pack has a weird configuration indeed :D

**Comment by luca992** [comment]
Huh, but if NavbarDropDown requires it to function shouldn't, shouldn't the NavbarDropDown be one of the components which triggers the import on the library side?

**Comment by hfhbd** [comment]
Yes, that`s true, so the issue is still open.
