### ISSUE TITLE
Change the default bootstrap theme colors

### ISSUE THREAD

**Issue by hfhbd** [hfhbd/bootstrap-compose#187]
### Discussed in https://github.com/hfhbd/bootstrap-compose/discussions/186

<div type='discussions-op-text'>

<sup>Originally posted by **luca992** May 13, 2022</sup>
Just wondering, what would be the best way to change the default theme colors that are defined by bootstrap?

Found instructions for a normal project.
https://stackoverflow.com/questions/38792005/how-to-change-the-bootstrap-primary-color

But, I'm not sure how I can translate that to a kotlin project.</div>

- [ ] Readme
- [ ] Provide a `StyleSheet` class

**Comment by luca992** [comment]
Work great, thanks! 👍
