### ISSUE TITLE
Icons: resizing and color

### ISSUE THREAD

**Issue by luca992** [hfhbd/bootstrap-compose#227]
I tried out the new icons which is nice, but it doesn't allow you to change it's attributes. It would be nice to be apply have attrs exposed to be able to resize them and change colors.

**Comment by hfhbd** [comment]
Oh, totally forgot to add the attrs parameter 🤦🏻‍♂️

**Comment by luca992** [comment]
haha, whenever you have the chance to add it, it would be a appreciated.
