### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by Debdutta-Panda** [hfhbd/bootstrap-compose#299]
![image](https://user-images.githubusercontent.com/92369023/215268057-2db4b969-e1d6-44a4-83de-27e6f4686e19.png)
Showing this error

**Comment by hfhbd** [comment]
Please provide a reproducer.

**Comment by Debdutta-Panda** [comment]
Look this project https://github.com/Debdutta-Panda/demoCoposeBootstrap

**Comment by Debdutta-Panda** [comment]
Have tried with this as well:
```
afterEvaluate {
    rootProject.extensions.configure<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension> {
        versions.webpackDevServer.version = "4.11.1"
        versions.webpackCli.version = "5.0.1"
    }
}
```
But same problem

**Comment by hfhbd** [comment]
Use webpack 5:
Remove `kotlin.js.webpack.major.version=4` in gradle.properties and remove 
```
afterEvaluate {
    rootProject.extensions.configure<org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootExtension> {
        versions.webpackDevServer.version = "4.11.1"
        versions.webpackCli.version = "5.0.1"
    }
}
```

**Comment by Debdutta-Panda** [comment]
Hi, @hfhbd as of now there are no solution for that problem right? If yes then you should say this explicitly, then you should close the issue. **_Otherwise this is just an unrelieable library._**
