### ISSUE TITLE
If Container fluid = true, both the "container" and "container-fluid" classes are applied

### ISSUE THREAD

**Issue by gsteckman** [hfhbd/bootstrap-compose#36]
If fluid==true, the "container" class should not be applied. Instead only the "container-fluid" class should be applied.

**Comment by hfhbd** [comment]
This should also be true when `container-md` is wanted. `container-fluid` and `container-md` should also not be possible.

**Comment by hfhbd** [comment]
Fixed in `v0.0.20`
