### ISSUE TITLE
Support for npm vs yarn

### ISSUE THREAD

**Issue by luca992** [hfhbd/bootstrap-compose#386]
I'd like to use the new `kotlin.js.yarn=false` option in kotlin 2.0 and my project won't compile with bootstrap-compose added. I'm not sure It's possible to support both, but use of yarn is being depreciated in upcoming kotlin versions from what I read.

**Comment by hfhbd** [comment]
Can you provide a reproducer cause switching from Yarn to NPM only should not break Kotlin JS usage (even if it uses npm deps). Or do you also switch to ES modules etc.?

**Comment by luca992** [comment]
Just setting `kotlin.js.yarn=false` causes this:

```
# npm resolution error report

While resolving: bootstrap-compose@0.2.0
Found: @popperjs/core@2.11.5
node_modules/@popperjs/core
  @popperjs/core@"2.11.5" from bootstrap-compose@0.2.0
  packages_imported/bootstrap-compose/0.2.0
    bootstrap-compose@0.2.0
    node_modules/bootstrap-compose
      workspace packages_imported/bootstrap-compose/0.2.0 from the root project

Could not resolve dependency:
peer @popperjs/core@"^2.11.6" from bootstrap@5.2.3
node_modules/bootstrap
  bootstrap@"5.2.3" from bootstrap-compose@0.2.0
  packages_imported/bootstrap-compose/0.2.0
    bootstrap-compose@0.2.0
    node_modules/bootstrap-compose
      workspace packages_imported/bootstrap-compose/0.2.0 from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

I added bootstrap-compose here and it is reproducible
https://github.com/luca992/KMP-App-Template/tree/bootstrap-compose-error
