### ISSUE TITLE
Bootstrap CSS Import

### ISSUE THREAD

**Issue by hfhbd** [hfhbd/bootstrap-compose#95]
- dynamic import: https://github.com/mpetuska/kamp/blob/6bdcd2f123c9b4298ef4881069b94532a929938b/app/client/kmdc/src/jsMain/kotlin/button/MDCButton.kt#L15
Possible with one css file?

- Alternative: Read CSS file and convert it to Kotlin to use it with typed classes and code shrinker? (dukat for CSS...)

**Comment by gsteckman** [comment]
See also [https://github.com/JetBrains/compose-jb/issues/1371](https://github.com/JetBrains/compose-jb/issues/1371)

**Comment by hfhbd** [comment]
Related to #187
